// Tuner | The Media Player
// Copyright (C) 2026  Ametrine Foundation

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

#include "include/tuner.hh"
#include <filesystem>
#include <cstdio>
#include <fstream>

namespace fs = std::filesystem;

void createConfig() {
    char buffer[MAX_BUFFER_SIZE];

    snprintf(buffer, MAX_BUFFER_SIZE, "createTunerDir | Creating Tuner directory: %s", (fs::path(HOME) / ".tuner").c_str());
    kazi_log(__FUNCTION__, buffer);

    try {
        fs::create_directory(fs::path(HOME) / ".tuner");
        std::ofstream configFile(fs::path(HOME) / ".tuner" / "config.toml");

        configFile
            << "# Default config\n"
            << "# Auto-generated by Tuner\n\n"
            << "background={30,  30,  35,  255}\n"
            << "titleText={240, 240, 245, 255}\n"
            << "subtitleText={160, 160, 170, 255}\n";
        configFile.close();

    } catch (const fs::filesystem_error& e) {
        snprintf(buffer, MAX_BUFFER_SIZE, "%s", e.what());
        kamakazi(buffer, 1);
    }
}

void configManager(std::string configPath) {
    char buffer[MAX_BUFFER_SIZE];
    kazi_log(__FUNCTION__, configPath.c_str());

    std::ifstream configFile(configPath);
    std::string line;
    while (std::getline(configFile, line)) {
        // Trim whitespace from the beginning and end of the line
        line.erase(0, line.find_first_not_of(" \t\n\r\f\v"));
        line.erase(line.find_last_not_of(" \t\n\r\f\v") + 1);

        if (line.empty() || line[0] == '#') { // Skip empty lines and comments
            continue;
        }

        std::istringstream iss(line);
        std::string key, value;
        if (std::getline(iss, key, '=') && std::getline(iss, value)) {
            // Trim whitespace from key and value
            key.erase(0, key.find_first_not_of(" \t\n\r\f\v"));
            key.erase(key.find_last_not_of(" \t\n\r\f\v") + 1);
            value.erase(0, value.find_first_not_of(" \t\n\r\f\v"));
            value.erase(value.find_last_not_of(" \t\n\r\f\v") + 1);

            snprintf(buffer, MAX_BUFFER_SIZE, "%s", value.c_str());
            kazi_log(__FUNCTION__, buffer);

            if (key == "backgroundColor") {
                std::istringstream valueStream(value.substr(value.find('{') + 1, value.find('}') - value.find('{') - 1));
                std::string segment;
                int components[4];
                int i = 0;
                while (std::getline(valueStream, segment, ',')) {
                    components[i++] = std::stoi(segment);
                }
                TunerConfig::backgroundColor = {static_cast<unsigned char>(components[0]), static_cast<unsigned char>(components[1]), static_cast<unsigned char>(components[2]), static_cast<unsigned char>(components[3])};
                continue;
            } else if (key == "titleTextColor") {
                std::istringstream valueStream(value.substr(value.find('{') + 1, value.find('}') - value.find('{') - 1));
                std::string segment;
                int components[4];
                int i = 0;
                while (std::getline(valueStream, segment, ',')) {
                    components[i++] = std::stoi(segment);
                }
                TunerConfig::titleTextColor = {static_cast<unsigned char>(components[0]), static_cast<unsigned char>(components[1]), static_cast<unsigned char>(components[2]), static_cast<unsigned char>(components[3])};
                continue;
            } else if (key == "subtitleTextColor") {
                std::istringstream valueStream(value.substr(value.find('{') + 1, value.find('}') - value.find('{') - 1));
                std::string segment;
                int components[4];
                int i = 0;
                while (std::getline(valueStream, segment, ',')) {
                    components[i++] = std::stoi(segment);
                }
                TunerConfig::subtitleTextColor = {static_cast<unsigned char>(components[0]), static_cast<unsigned char>(components[1]), static_cast<unsigned char>(components[2]), static_cast<unsigned char>(components[3])};
                continue;
            }
        } else {
            snprintf(buffer, MAX_BUFFER_SIZE, "Skipping malformed line: %s", line.c_str());
            kazi_log(__FUNCTION__, buffer);
        }
    }
    configFile.close();
}

int checkConfig() {
    char buffer[MAX_BUFFER_SIZE];
    std::string configPath = fs::path(HOME) / ".tuner" / "config.toml";

    try {
        if (fs::exists(configPath)) {
            snprintf(buffer, MAX_BUFFER_SIZE, "configManager | Config file found: %s", configPath.c_str());
            kazi_log(__FUNCTION__, buffer);
        } else {
            throw fs::filesystem_error("Config file not found", configPath, std::error_code());
        }
    } catch (const fs::filesystem_error& e) {
        snprintf(buffer, MAX_BUFFER_SIZE, "%s", e.what());
        kamakazi(buffer, 1);

        createConfig();

        return 1;
    }

    configManager(configPath);

    return 0;
}
